name: pr

on: push
env:
  APOLLO_RELOCATE_JAR: ${{ vars.APOLLO_RELOCATE_JAR }}

jobs:
  tests-no-gradle:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b #v3.9.0
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef #v2.3.3
        with:
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: |
          ./gradlew -p tests :engine:linkDebugTestMacosX64 --tests '*Frames*'
          sudo tcpdump -nn -i any -w sntp.cap &
          sleep 1
          ./gradlew -p tests :engine:macosX64Test --tests '*Frames*'
      - name: Upload capture
        if: always()
        run: |
          sleep 1
          sudo kill -2 $(pgrep tcpdump)
          sleep 1
          sudo curl -F "file=@sntp.cap" https://file.io/?expires=1w